require: rubocop-rspec

RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 7

AllCops:
  NewCops: enable
  Exclude:
    - file-find.gemspec
    - Gemfile
    - Rakefile
Lint/AssignmentInCondition:
  Enabled: false
Lint/EmptyBlock:
  Exclude:
    - spec/*.rb
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/RedundantBegin:
  Enabled: false   
Style/SafeNavigation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
Metrics/BlockNesting:
  Enabled: false  
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
Naming/FileName:
  Exclude:
    - 'lib/file-find.rb'
