name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', '3.4', 'jruby', 'truffleruby']
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Setp Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        if: matrix.platform == 'windows-latest'
        run: gem install win32-security
    - name: Run tests
      run: bundle exec rake
